ALTER TABLE auth_users ADD COLUMN language VARCHAR(10) NOT NULL DEFAULT 'VI';
ALTER TABLE auth_users ADD COLUMN theme VARCHAR(20) NOT NULL DEFAULT 'LIGHT';
ALTER TABLE auth_users ADD COLUMN notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE auth_users ADD COLUMN email_notifications BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE auth_users ADD COLUMN sms_notifications BOOLEAN NOT NULL DEFAULT TRUE;
