spring.application.name=autowash-backend

spring.datasource.url=${AUTOWASH_DB_URL:jdbc:postgresql://localhost:5432/autowash}
spring.datasource.username=${AUTOWASH_DB_USERNAME:autowash}
spring.datasource.password=${AUTOWASH_DB_PASSWORD:autowash}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html

