spring.application.name=autowash-backend

spring.datasource.url=${AUTOWASH_DB_URL:jdbc:postgresql://localhost:5432/autowash}
spring.datasource.username=${AUTOWASH_DB_USERNAME:postgres}
spring.datasource.password=${AUTOWASH_DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=${AUTOWASH_H2_CONSOLE_ENABLED:false}
spring.h2.console.path=/h2-console

springdoc.swagger-ui.path=/swagger-ui.html
